name: openapi_repository
description: This package generates ListBloc and DataBloc using openapi_repository_annotations.
version: 3.1.2
homepage: https://github.com/djangoflow/list_bloc/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^5.2.0
  build: ^2.3.0
  built_collection: ^5.1.1
  built_value: ^8.6.1
  collection: ^1.17.1
  dio: ^5.2.1+1
  freezed_annotation: ^2.2.0
  list_bloc: ^3.1.0
  mustache_template: ^2.0.0
  openapi_repository_annotations: ^1.2.2
  path: ^1.8.3
  recase: ^4.1.0
  source_gen: ^1.3.2
  _openapi_repository_internal_models: ^0.0.3

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  lints: ^2.1.1
  test: ^1.24.3
