name: openapi_repository
description: This package generates ListBloc and DataBloc using openapi_repository_annotations.
version: 3.4.2
homepage: https://github.com/djangoflow/list_bloc/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^5.13.0
  build: ^2.4.1
  built_collection: ^5.1.1
  built_value: ^8.6.2
  collection: ^1.17.2
  freezed_annotation: ^2.4.1
  mustache_template: ^2.0.0
  openapi_repository_annotations: ^1.2.3
  path: ^1.8.3
  recase: ^4.1.0
  source_gen: ^1.4.0
  _openapi_repository_internal_models: ^0.0.3+1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  lints: ^2.1.1
  test: ^1.24.6
