name: openapi_repository
description: This package generates ListBloc and DataBloc using openapi_repository_annotations.
version: 3.4.5
homepage: https://github.com/djangoflow/list_bloc/
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: any
  build: any
  built_collection: any
  built_value: any
  collection: any
  freezed_annotation: any
  mustache_template: any
  path: any
  recase: any
  source_gen: any
  _openapi_repository_internal_models: any

  openapi_repository_annotations:
    git:
      url: https://github.com/ccappflow/list_bloc
      path: packages/openapi_repository_annotations

dev_dependencies:
  build_runner: any
  freezed: any
  json_serializable: any
  lints: any
  test: any
