name: openapi_repository_annotations
description: Annotation to generate ListBloc and DataBloc. Should be used with openapi_repository package.
version: 1.2.2
homepage: https://github.com/djangoflow/list_bloc/

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
