name: list_bloc
description: A BLoC library for loading data from an api end-point with filtering and pagination.
version: 3.1.3
homepage: https://github.com/djangoflow/list_bloc/

environment:
  sdk: ^3.6.0

dependencies:
  bloc: any
  freezed_annotation: any

dev_dependencies:
  lints: any
  test: any
  build_runner: any
  freezed: any
  equatable: any
  bloc_test: any

